blank_issues_enabled: true
contact_links:
  - name: Questions and Discussions
    url: https://github.com/AbdelStark/mikan/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/AbdelStark/mikan#readme
    about: Check the documentation before reporting an issue.